### ISSUE TITLE
RSS link broken

### ISSUE THREAD

**Issue by jabranham** [bapfeld/bapfeld.github.io#1]
Just saw you started a blog and tried to add it to my RSS reader. The link doesn't work though. I think in `blog.html` if you replace:

```
 <p class="rss-subscribe">subscribe <a href="{{ "/feed.xml" | prepend: site.baseurl }}">via RSS</a></p>
```

with this
```
 <p class="rss-subscribe">subscribe <a href="{{ "/atom.xml" | prepend: site.baseurl }}">via RSS</a></p>
```

Then it will work?

**Comment by bapfeld** [comment]
Ok thanks for letting me know! I may fix that eventually. I don't really want it to be a true blog and I certainly don't plan on posting anything frequently. But I guess I can update that pretty quickly. I suspect there are deeper issues at play in this problem as well- the template I used is very strange in a lot of ways.

**Comment by jabranham** [comment]
No worries. Ran across that issue when I was avoiding grading.

**Comment by bapfeld** [comment]
Should be fixed, thanks for catching that!
